# Generated by Django 5.2.7 on 2025-10-07 00:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('category', models.CharField(choices=[('pisciculture', 'Pisciculture'), ('agriculture', 'Agriculture'), ('elevage', 'Élevage'), ('autres', 'Autres')], default='autres', max_length=32, verbose_name='Catégorie')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Titre')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Fichier image')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('video', models.FileField(upload_to='videos/', verbose_name='Fichier vidéo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=100)),
                ('response', models.TextField(blank=True)),
                ('content', models.TextField(verbose_name='Commentaire')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Commentaire admin')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='academy.formation')),
            ],
        ),
        migrations.CreateModel(
            name='FormationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Nom image')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description image')),
                ('image', models.ImageField(upload_to='formations/images/', verbose_name='Fichier image')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('formation', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='academy.formation')),
            ],
        ),
        migrations.CreateModel(
            name='FormationVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('video', models.FileField(upload_to='videos/', verbose_name='Fichier vidéo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
                ('formation', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='academy.formation')),
            ],
        ),
    ]
